###  1) Create a vector (array) of 1XN dimension representing N-dimensional feature vector of a sample. Write a program to compute the mean and variance of the elements present in the array.

In [24]:
import numpy as np

# Define the dimension of the feature vector
N = 50

# Create a random feature vector of dimension 1xN
feature_vector = np.random.rand(1, N)

# Compute mean and variance of the feature vector
mean = np.mean(feature_vector)
variance = np.var(feature_vector)

# Print mean and variance
print("Mean of the feature vector:", mean)
print("Variance of the feature vector:", variance)


Mean of the feature vector: 0.49182911628360976
Variance of the feature vector: 0.0697848930684446


### 2) Create two vectors each of dimension 1XM each representing N-dimensional feature vector of a sample. Write a program to compute the Covariance between them.

In [26]:
# Define the dimensions of the feature vectors
n=30
m=30

# Create two random feature vectors of dimensions 1xM and 1xN
fv1 = np.random.rand(1,n)
fv2 = np.random.rand(1,m)

# Compute covariance between the two feature vectors
covariance = np.cov(fv1,fv2)
print(covariance)
Cov = covariance[0,1]
Cov

[[ 0.09601541 -0.00755372]
 [-0.00755372  0.06844048]]


-0.007553717899180749

### 3) Create two vectors each of dimension 1XN. Write a program to compute the Correlation between them.

In [27]:
correlation = np.corrcoef(fv1,fv2)
print(correlation)
Corel = correlation[0][1]
Corel

[[ 1.         -0.09318237]
 [-0.09318237  1.        ]]


-0.09318237281777333

### 4) Create a Matrix of MXN dimension representing the M-dimensional feature vector for N number of samples i. e (i,j)th entry of the matrix represents the ith feature of jth sample. Write a program to compute the covariance matrix and correlation matrix. Comment on takeaways from these matrixes.

In [22]:
# Define the dimensions of the feature matrix
M = 3  # Number of features
N = 5  # Number of samples

# Create a matrix representing feature vectors for N samples
data_matrix = np.random.rand(M, N)

# Compute covariance matrix
covariance_matrix = np.cov(data_matrix)

# Compute correlation matrix
correlation_matrix = np.corrcoef(data_matrix)

# Print covariance matrix
print("Covariance matrix:")
print(covariance_matrix)

Covariance matrix:
[[0.06792124 0.02891624 0.00300271]
 [0.02891624 0.0765067  0.01641186]
 [0.00300271 0.01641186 0.08132587]]
